project:
  type: website
  output-dir: docs

website:
  title: "431-2024"
  page-footer: "Fall 2024: PQHS/CRSP/MPHP 431 at CWRU with Professor Love"
  navbar:
    background: "#702963"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - text: "Syllabus"
        href: ph.qmd
      - text: "Course Notes"
        href: https://thomaselove.github.io/431-book/
      - text: "Assignments"
        href: assignments.qmd
      - text: "Software"
        href: software.qmd
      - text: "Campuswire"
        href: ph.qmd
    right:
      - text: "Key Links"
        menu: 
        - text: "431-Data page"
          href: https://github.com/THOMASELOVE/431-data
        - text: "431 R packages"
          href: https://github.com/THOMASELOVE/431-packages
        - text: "Minute Papers (Github)"
          href: https://github.com/THOMASELOVE/431-minute-2024
        - text: "Labs (Github)"
          href: https://github.com/THOMASELOVE/431-labs-2024
        - text: "Quizzes (Github)"
          href: https://github.com/THOMASELOVE/431-quizzes-2024
        - text: "Project A (Github)"
          href: https://thomaselove.github.io/431-projectA-2024/
        - text: "Project B (Github)"
          href: ph.qmd  
      - text: "Contact Us"
        href: contact.qmd
        
format:
  html:
    theme: 
      light: litera
      dark: cyborg
    date-format: iso
    toc: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true

editor: source

