# Assignments for 431 in Fall 2024

This page links to all instructions and other information about course assignments. All deadlines are found on the [Course Calendar](calendar.qmd).

::: {.callout-important}

## This page is mostly complete, but still under construction.

We will post almost all class materials for 431 before the class begins on 2024-08-27. Most of what's here shouldn't change, but some things might. Missing things and dead links should be resolved over the next few days. If you have questions, contact Dr. Love at `Thomas dot Love at case dot edu`.

:::

## Labs

The general page for all [431 Labs is here](https://github.com/THOMASELOVE/431-labs-2024/blob/main/README.md). We'll post links to each specific lab page below as they become available.

- [Lab 0: Welcome to 431 Survey](https://bit.ly/431-2024-welcome)
    - Note: You must log into Google via CWRU in order to access the Survey.
- [Lab 1 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab1) on Github
- [Lab 2 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab2) on Github
- [Lab 3 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab3) on Github
- [Lab 4 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab4) on Github
- [Lab 5 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab5) on Github
- [Lab 6 page](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab6) on Github
- [Lab 7](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab7) (Developing a Personal Website) on Github

## Minute Papers

- [Minute Papers page](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) on Github

## Quizzes

The general page for both [431 Quizzes is here](https://github.com/THOMASELOVE/431-quizzes-2024/blob/main/README.md). We'll post links to each specific quiz page below as they become available.

- Quiz 1 page on Github
- Quiz 2 page on Github

## Projects

- The [Project A page](https://thomaselove.github.io/431-projectA-2024/) with all instructions and materials related to Project A is now available.
- The Project B page will appear later this year.
