---
title: "Course Calendar"
date: last-modified
---

All class sessions will be held from 1:00 to 2:15 PM in Room E321-323 on the third floor of the Robbins building at CWRU's School of Medicine.

Readings come from:

- **Spiegelhalter**: David Spiegelhalter's [The Art of Statistics: How to Learn from Data](https://www.amazon.com/Art-Statistics-How-Learn-Data/dp/1541675703) originally published in 2020 and available at all major book retailers.
- **R4DS**: R for Data Science (2nd edition), found at <https://r4ds.hadley.nz/>.
- **TEL**: Dr. Love's [Course Book](https://thomaselove.github.io/431-book/)

## August

Class | Day | Date | Additional Information
:-----: | ---: | ---------- | ----------------------------
[Class 01](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class01) | TU | 2024-08-27 | Getting Started (TEL 1-2)
**deadline** | **W** | 2024-08-28 | [Lab 0: Welcome to 431 Survey](https://bit.ly/431-2024-welcome) due at noon
[Class 02](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class02) | TH | 2024-08-29 | Data Visualization and Summary (TEL 2-3)
*reading* | -- | by Class 3 | Spiegelhalter: Introduction and Chapter 1 <br /> R4DS: Introduction and as much of "Whole game" as possible <br /> skim through the [Project A](https://thomaselove.github.io/431-projectA-2024/) instructions

## September

Class | Day | Date | Additional Information
-----: | ---: | ---------- | ----------------------------
[Class 03](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class03) | TU | 2024-09-03 | Data Wrangling (TEL 4)
**deadline** | **W** | 2024-09-04 | [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 09-04 due at noon
[Class 04](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class04) | TH | 2024-09-05 | Comparing Paired Samples (TEL 5)
*reading* | -- | by Class 5 | Spiegelhalter: Chapters 2 and 3 <br /> R4DS:  remainder of "Whole game" (Sections 1-8) <br /> get going on [Project A](https://thomaselove.github.io/431-projectA-2024/) Data work
[Class 05](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class05) | TU | 2024-09-10 | Comparing Independent Samples (TEL 6)
**deadline** | **W** | 2024-09-11 | [Lab 1](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab1) due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 09-11 due at noon
[Class 06](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class06) | TH | 2024-09-12 | Transformation (TEL 7)
*reading* | -- | by Class 7 | Spiegelhalter: Chapter 5 <br /> R4DS:  "Visualize" sections, especially sections 10 and 11 <br /> finish the [Project A](https://thomaselove.github.io/431-projectA-2024/) Data work and start the Plan. 
[Class 07](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class07) | TU | 2024-09-17 | Comparing Multiple Groups (TEL 9)
**deadline** | **W** | 2024-09-18 | [Lab 2](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab2) due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 09-18 due at noon
[Class 08](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class08) | TH | 2024-09-19 | Extensions of One-Factor ANOVA (TEL 10)
*reading* | -- | by Class 9 | Spiegelhalter: Chapter 7 <br /> R4DS: Sections 16 (Factors) and 28 (Quarto) <br /> Complete the [Project A Plan](https://thomaselove.github.io/431-projectA-2024/): due Wednesday!
[Class 09](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class09) | TU | 2024-09-24 | Association and Correlation (TEL 11-12)
**deadline** | **W** | 2024-09-25 | [Project A Plan](https://thomaselove.github.io/431-projectA-2024/) due at noon 
[Class 10](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class10) | TH | 2024-09-26 | On Weighting (TEL 8) and Catchup

## October

Class | Day | Date | Additional Information
-----: | ---: | ---------- | ----------------------------
*reading* | -- | by Class 11 | Spiegelhalter: Chapter 8 
[Class 11](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class11) | TU | 2024-10-01 | Two-by-Two Tables (TEL 13)
**deadline** | **W** | 2024-10-02 | [Lab 3](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab3) due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 10-02 due at noon
[Class 12](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class12) | TH | 2024-10-03 | Larger Two-Way Cross-Classifications (TEL 14)
*reading* | -- | by Class 13 | Spiegelhalter: Chapter 9 <br /> get started on [Project A](https://thomaselove.github.io/431-projectA-2024/) Analyses
[Class 13](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class13) | TU | 2024-10-08 | What's wrong with Statistical Significance, 1 (TEL 15)
**deadline** | **W** | 2024-10-09 | [Lab 4](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab4) due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 10-09 due at noon
[Class 14](https://github.com/THOMASELOVE/431-classes-2024/tree/main/class14) | TH | 2024-10-10 | What's wrong with Statistical Significance, 2 (TEL 15) <br> Quiz 1 out to students at 5 PM
*reading* | -- | by Class 15 | Spiegelhalter: Chapter 10
15 | TU | 2024-10-15 | Adjusting for a covariate (TEL 16)
**deadline** | **W** | 2024-10-16 | Quiz 1 due at noon 
16 | TH | 2024-10-17 | Covariate Adjustment in Simpler Models (TEL 17)
-- | M | 2024-10-21 | CWRU Fall Break - TA office hours canceled.
-- | TU | 2024-10-22 | CWRU Fall Break - no 431 class, and TA office hours canceled.
*reading* | -- | by Class 17 | Spiegelhalter: Chapter 11 <br /> complete most of the [Project A](https://thomaselove.github.io/431-projectA-2024/) Portfolio report
17 | TH | 2024-10-24 | Ask Me Anything / [Project A](https://thomaselove.github.io/431-projectA-2024/) Help Session
*reading* | -- | by Class 18 | Spiegelhalter: Chapter 12
18 | TU | 2024-10-29 | Regression Using Two Quantities (TEL 18)
**deadline** | **W** | 2024-10-30 | [Project A](https://thomaselove.github.io/431-projectA-2024/) Portfolio due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 10-30 due at noon
19 | TH | 2024-10-31 | Two-Factor Analysis of Variance (TEL 19)

## November

Class | Day | Date | Additional Information
-----: | ---: | ---------- | ----------------------------
-- | TU | 2024-11-05 | Election Day - no 431 class. <br /> (*TA office hours will be held.*)
**deadline** | **W** | 2024-11-06 | [Lab 5](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab5) due at noon
20 | TH | 2024-11-07 | Multiple Linear Regression, 1 (TEL 20)
*reading* | -- | by Class 21 | Spiegelhalter: Chapter 13
21 | TU | 2024-11-12 | Multiple Linear Regression, 2 (TEL 20-21)
**deadline** | **W** | 2024-11-13 | Project B Plan due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 11-13 due at noon
22 | TH | 2024-11-14 | Multiple Linear Regression, 3 (TEL 20-22)
-- | F | 2024-11-15 | Schedule for Project B Presentations announced
*reading* | -- | by Class 23 | Spiegelhalter: Chapter 4
23 | TU | 2024-11-19 | Multiple Linear Regression, 4 (TEL 20-22)
**deadline** | **W** | 2024-11-20 | [Lab 6](https://github.com/THOMASELOVE/431-labs-2024/tree/main/lab6) due at noon <br> [Minute Paper](https://github.com/THOMASELOVE/431-minute-2024/blob/main/README.md) 11-20 due at noon
24 | TH | 2024-11-21 | Multiple Linear Regression, 5 (TEL 20-22) <br> Quiz 2 out to students at 5 PM
-- | SA | 2024-11-23 | TA office hours canceled 11-23 through 11-30
-- | TU | 2024-11-26 | Thanksgiving Week - no 431 class.
-- | TH | 2024-11-28 | CWRU Thanksgiving Break - no 431 class.

## December

Class | Day | Date | Additional Information
-----: | ---: | ---------- | ----------------------------
-- | SU | 2024-12-01 | TA office hours resume.
*reading* | -- | by Class 25 | Spiegelhalter: rest of book (chapters 6 and 14)
25 | TU | 2024-12-03 | Summary Case Study (also see TEL 23)
**deadline** | **W** | 2024-12-04 | Quiz 2 due at noon <br> Lab 7 due at noon
26 | TH | 2024-12-05 | What happened here? What's in 432?
-- | F | 2024-12-06 | Project B presentations: Day 1
-- | M | 2024-12-09 | Last Day for TA office hours. <br /> Project B presentations: Day 2
-- | TU | 2024-12-10 | Project B presentations: Day 3
-- | W | 2024-12-11 | Project B presentations: Day 4
**deadline** | **W** | 2024-12-11 | Project B Portfolio submitted by noon. <br> (Optional) Lab Regrade Request Form due at noon.

:::{.callout-important}

Project B presentations will be scheduled on 2024-11-15, and held over parts of four days between Friday 2024-12-06 and Wednesday 2024-12-11. 

- You will be able to give your presentation either in person or over Zoom, and your total time commitment will be one hour on one of those four days.

:::

## Getting Help

Visit the [Contact Us page](contact.qmd) for ways to get help in this class.

## TA Office Hours

TA office hours are held via Zoom, and will begin on **Tuesday 2023-09-03** and will continue through Monday 2023-12-09. Our Shared Google Drive (431 Fall 2024 Dr Love and Students) displays Zoom links for all TA office hours in a document called **TA office hours schedule and Zoom links**. [Or see that document (pdf) here](office_hours_2024.pdf). No appointment is necessary. Please just drop in.

TA office hours will be held at the following times. 

SUN | MON | TUE | THU | FRI
:------: | :------: | :------: | :------: | :------:   
5:00 PM - 6:30 PM | 11:45 AM - 12:45 PM | 11:45 AM - 12:45 PM | 7:30 PM - 9:00 PM | 12:30 PM - 2:00 PM
7:00 PM - 8:30 PM | 5:30 PM - 7:00 PM | 5:30 PM - 7:00 PM | 
8:30 PM - 10:00 PM | 7:30 PM - 9:00 PM | 7:30 PM - 9:00 PM | 

- Professor Love will also hold “drop-in hours” for 10 minutes before and for 30 minutes after each class on Tuesdays and Thursdays.
- Office hours are canceled on 2024-10-21 and 2024-10-22 (Fall Break) and from 2024-11-23 through 2024-11-30 (Thanksgiving)

::: {.callout-note}
We have no scheduled TA office hours on Wednesdays or Saturdays.

Essentially all deliverables for 431 are due at noon on Wednesdays, so that's why we have our office hours scheduled as they are.
:::

- More information on each of this semester's TAs is in [this section of our Syllabus](https://thomaselove.github.io/431-syllabus-2024/08_teachingassistants.html).
