---
title: "Campuswire"
date: last-modified
---


## Signing Up for Campuswire

Visit <https://campuswire.com/p/G1B70B9D9> to sign up. When you do this, you'll need a four-digit class join code, which is **7781**.

Be sure to sign in with your full name (rather than a nickname) and an email address that you will check daily. 

- Ideally, you would use your CWRU email, or at least the same email address you indicated that you preferred on the [Welcome to 431 survey](https://bit.ly/431-2024-welcome).

## Accessing Campuswire once you’ve signed up

Once you’re signed up, you can get to Campuswire by clicking on Sign In at <https://campuswire.com/>.

## How we’ll use Campuswire

After our first class session on August 27, we'll use Campuswire to facilitate questions and answers. We'll be conducting as much of our class-related discussion there as possible, instead of via email. It’s open 24 hours a day, 7 days a week.

If you're successfully enrolled in the class, you should be able to sign up immediately, and gain access to Professor Love’s 431 course.

The quicker you begin asking questions on Campuswire (rather than via emails), the quicker you'll benefit from the collective knowledge of your classmates, teaching assistants and Professor Love.

We encourage you to ask questions when you're struggling to understand anything related to the class, and you can even do so anonymously.

You'll also be able to help your colleagues by answering their questions (and you'll get some class participation credit for doing so.)
