---
title: "Contact Us"
date: last-modified
---

## Before class begins on 2024-08-27

If you have any questions before class begins, contact Professor Love at `thomas dot love at case dot edu`.

## Once The Class Begins

If you’ve spent 15 minutes working on something and are stuck, don’t keep working on it. ASK FOR HELP. To get help in this course, you have three main options:

1. Use our [Campuswire](campuswire.qmd) discussion board to ask (and answer) questions about the course. This is available 24 hours a day, 7 days a week, starting **after our first class**. The system is highly catered to getting you help fast and efficiently from classmates, the TA, and myself. Rather than emailing questions to the teaching staff, I encourage you to post your questions on Campuswise. Sign up for Campuswire at the [link provided here](campuswire.qmd).

2. Attend TA office hours to get one-on-one help or share a computer problem.

TA office hours are held via Zoom, and will begin on **Tuesday 2023-09-03** and will continue through Monday 2023-12-09. Our Shared Google Drive (431 Fall 2024 Dr Love and Students) displays Zoom links for all TA office hours in a document called **TA office hours schedule and Zoom links**. [Or see that document (pdf) here](office_hours_2024.pdf). No appointment is necessary. Please just drop in.

TA office hours will be held at the following times. 

SUN | MON | TUE | THU | FRI
:------: | :------: | :------: | :------: | :------:   
5:00 PM - 6:30 PM | 11:45 AM - 12:45 PM | 11:45 AM - 12:45 PM | 9:00 PM - 10:30 PM | 12:30 PM - 2:00 PM
7:00 PM - 8:30 PM | 5:30 PM - 7:00 PM | 5:30 PM - 7:00 PM | 
8:30 PM - 10:00 PM | 7:30 PM - 9:00 PM | 7:30 PM - 9:00 PM | 

- Professor Love will also hold “drop-in hours” for 10 minutes before and for 30 minutes after each class on Tuesdays and Thursdays.
- Office hours are canceled on 2024-10-21 and 2024-10-22 (Fall Break) and from 2024-11-23 through 2024-11-30 (Thanksgiving)

::: {.callout-note}
We have no scheduled TA office hours on Wednesdays or Saturdays.

Essentially all deliverables for 431 are due at noon on Wednesdays, so that's why we have our office hours scheduled as they are.
:::

- More information on each of this semester's TAs is in [this section of our Syllabus](https://thomaselove.github.io/431-syllabus-2024/08_teachingassistants.html).

3. Email Professor Love at `Thomas dot Love` at `case dot edu` with any individual concerns related to the course that you do not feel comfortable asking elsewhere, or if you have any special concerns or needs that you want him to know about, or to set up an appointment with him for a Zoom meeting.