---
title: "431 Course Main Page: Fall 2024"
author: "Thomas E. Love"
date: last-modified
---

# Welcome! 

431 is the first part of a two-semester sequence (with 432) in applied statistics and data science taught by Professor Thomas Love in the [Department of Population and Quantitative Health Sciences](https://case.edu/medicine/pqhs/) at [Case Western Reserve University](https://case.edu/).

## Getting Started

Your first few steps in this course are to:

1. Register and enroll via the [CWRU Student Information System (SIS)](https://sis.case.edu/).
2. Take a look at this website. Of particular importance is the Getting Started section you're reading now, and the [Course Calendar](calendar.qmd), but a lot of other material is available now, and more will appear as we approach the first day of class next Tuesday August 27.
3. Obtain a copy of David Spiegelhalter's [The Art of Statistics: How to Learn from Data](https://www.amazon.com/Art-Statistics-How-Learn-Data/dp/1541675703), originally published in 2020 and available at all major book retailers for less than \$20.
4. Visit <https://bit.ly/431-2024-welcome> to complete the Welcome to 431 Survey, which is "Lab 0" for the course, technically due Wednesday August 28 at Noon, but we'd love to see you get this done before we start the class. Note: You must log into Google **via CWRU** in order to access the Survey.
5. You'll need to get R and RStudio on a computer you can control (including installing regular updates to the software) for the semester. You may want to get started on this process now - and installation details are found on our 431 [Software page](software.qmd). 
6. I also suggest you get started reading the first few sections (particularly the Introduction and Sections 1-2) of the online book [R for Data Science, 2nd Edition](https://r4ds.hadley.nz/).
7. Sign up for the [Campuswire discussion board at this link](campuswire.qmd).
8. Please visit [this link](https://case.edu/registrar/general/sis-resources/record-your-name-pronunciation) for information on how to record a pronunciation of your full name in the Student Information System so that all of your instructors (and fellow students) will be able to hear it.
9. Please log into Google via your CWRU account and ensure that you have access to a Shared Drive called **431 Fall 2024 Students and Dr. Love**.

## Everything will appear on this website

Materials that will appear here include:

-   the course [syllabus](https://thomaselove.github.io/431-syllabus-2024/)
-   the course [calendar](calendar.qmd), which is the final word on all deadlines, and also links to all materials used in each class session
-   Dr. Love's [431 book](https://thomaselove.github.io/431-book/) entitled "Foundations of Applied Statistics and R", which is a major source of course examples
-   detailed information on all course [assignments](assignments.qmd), with all deadlines found in the [calendar](calendar.qmd)
-   information on [software](software.qmd), including installation instructions for R, RStudio, and the key R packages and data sets we'll use
-   and information on how to [contact us](contact.qmd).

## NEW! [Go here](resources.qmd) for suggested R/RStudio/Quarto learning resources

## Class Starts Tuesday 2024-08-27 at 1 PM

Class will be held on Tuesdays and Thursdays from 1:00 - 2:15 PM in Room E321-E323 at CWRU's School of Medicine, starting on 2024-08-27.

## Questions?

If you have any questions before class begins, contact Professor Love at `thomas dot love at case dot edu`.

Thank you.
